#tag::setDatabaseName[]
spring:
  datasource:
    generate-unique-name: false
    name: f1dot5app
#    url: jdbc:sqlserver://localhost:1433;databaseName=WBA_ECommerce_F1dot5;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: тв008Ьщк142Ф
#end::setDatabaseName[]
